sonar.projectKey=instana-opentelemetry-go
sonar.projectName=instana-opentelemetry-go
sonar.sources=.
sonar.exclusions=**/*_test.go,**/test/**,**/mock_*.go,**/testdata/**,_scratch/**,dev/**,**/testutils.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.verbose=true
sonar.go.coverage.reportPaths=coverage.txt
sonar.links.homepage=https://github.ibm.com/instana/instana-opentelemetry-go
sonar.links.scm=https://github.ibm.com/instana/instana-opentelemetry-go
